# Generated by Django 5.0 on 2025-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_atividade_nota_atividade_preco_atividade_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais.', max_digits=10, verbose_name='Preço'),
        ),
    ]
