# Generated by Django 5.0 on 2025-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_alter_atividade_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='preco',
        ),
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='atividade',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='atividade',
            name='guia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='informacoes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='atividade',
            name='ingresso',
            field=models.BooleanField(default=False),
        ),
    ]
