# Generated by Django 5.0 on 2025-08-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_remove_atividade_preco_atividade_duracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(default='', help_text='Cidade onde mora atualmente.', max_length=255, verbose_name='Cidade')),
                ('pais', models.CharField(default='', help_text='País onde mora atualmente.', max_length=60, verbose_name='País')),
                ('bio', models.TextField(default='', help_text='Biografia do usuário.', verbose_name='Biografia')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('passaporte', models.CharField(default='', help_text='Número do passaporte.', max_length=10, verbose_name='Passaporte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
