# Generated by Django 5.0 on 2025-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OUTRO', 'Outro'), ('NOT_SPECIFIED', 'Não especificado')], default='NOT_SPECIFIED', max_length=20, verbose_name='Gênero'),
        ),
    ]
