# Generated by Django 5.0 on 2025-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0006_perfil_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
