# Generated by Django 5.0 on 2025-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_atividade_created_at_atividade_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('ingresso', models.BooleanField(default=False)),
                ('horario_funcinamento', models.CharField(blank=True, max_length=8, null=True, verbose_name='Horário de Funcionamento')),
                ('horario_fechamento', models.CharField(max_length=8, verbose_name='Horário de Fechamento')),
                ('nota', models.FloatField(default=0.0)),
                ('acessibiliade', models.BooleanField(default=False, verbose_name='Acessibilidade')),
                ('classificacao', models.BooleanField(default=False, verbose_name='Classificacao')),
                ('contato', models.EmailField(max_length=254, verbose_name='Email para Contato')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
