# Generated by Django 5.0 on 2025-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0009_pergunta_ranking_revisao_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
