# Generated by Django 5.0 on 2025-11-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0010_alter_ranking_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('generate_code', 'Can generate new codes')]},
        ),
    ]
