# Generated by Django 5.0 on 2025-09-17 14:40

import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.validatorcpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o titulo da reportagem.', max_length=50, verbose_name='Title')),
                ('pub_date', models.DateField(verbose_name='Published in')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validatorcpf.validate_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reporter name', max_length=100, verbose_name='Reporter')),
                ('cpf', models.CharField(max_length=11, validators=[relacionamentos.validators.validatorcpf.validate_cpf])),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='relacionamentos.Publication', to='relacionamentos.magazine', verbose_name='Magazines'),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter'),
        ),
    ]
