# Generated by Django 5.0 on 2025-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
    ]
